---
title: "quiz_gcd_week1"
author: "Derek Hall"
date: "5/1/2020"
output: pdf_document
---

# Question 1

How many properties are worth $1,000,000 or more?

```{r}
library(data.table)
download.file("https://d396qusza40orc.cloudfront.net/getdata%2Fdata%2Fss06hid.csv", destfile = "data/american_community_survey.csv")

acs_data <- fread("data/american_community_survey.csv")

q1 <- acs_data[VAL == 24, .N] 

q1
```

# Question 3

```{r}
download.file("https://d396qusza40orc.cloudfront.net/getdata%2Fdata%2FDATA.gov_NGAP.xlsx", destfile = "data/natgas_aquisition_prog.xlsx", mode = "wb")

library(xlsx)

dat <- read.xlsx("data/natgas_aquisition_prog.xlsx", 1, rowIndex = c(18:23), colIndex = c(7:15))

sum(dat$Zip*dat$Ext,na.rm=T)

```

# Question 4

```{r}
library(XML)
library(RCurl)

fileURL <- "https://d396qusza40orc.cloudfront.net/getdata%2Fdata%2Frestaurants.xml"

# We cannot use htmlTreeParse since it is https therefore use curl and getURL instead
# Instead we need to download it using getURL
xmlFile <- getURL(fileURL)

# And then parse the data into doc variable, we need to use htmlParse since this
# is an html file, but it contains embedded XML. useInternal = TRUE gets us all the
# different nodes inside that file
doc <- htmlParse(xmlFile, useInternal = TRUE)

rootNode <- xmlRoot(doc)

zip <- xpathSApply(rootNode, "//zipcode", xmlValue)

sum(zip == 21231)

```
```

